# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: athena_mars.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import waypoint_pb2 as waypoint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='athena_mars.proto',
  package='marsMessage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x61thena_mars.proto\x12\x0bmarsMessage\x1a\x0ewaypoint.proto\"\xb9\x01\n\x12Mars_General_Order\x12\x0f\n\x07trigger\x18\x01 \x01(\t\x12\x10\n\x08\x62\x65havior\x18\x02 \x01(\x05\x12\x1d\n\x15\x64riving_control_order\x18\x03 \x01(\x05\x12-\n\twaypoints\x18\x04 \x03(\x0b\x32\x1a.waypointMessages.Waypoint\x12\x18\n\x10\x65nabled_triggers\x18\x05 \x03(\t\x12\x18\n\x10\x63ontinuing_order\x18\x06 \x01(\t\"\xbd\x01\n\x0cMars_Message\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x0f\n\x07heading\x18\x04 \x01(\x02\x12\x19\n\x11\x62readcrumb_number\x18\x05 \x01(\x05\x12\x1d\n\x15\x63urrent_order_running\x18\x06 \x01(\t\x12/\n\x06orders\x18\x07 \x03(\x0b\x32\x1f.marsMessage.Mars_General_Orderb\x06proto3')
  ,
  dependencies=[waypoint__pb2.DESCRIPTOR,])




_MARS_GENERAL_ORDER = _descriptor.Descriptor(
  name='Mars_General_Order',
  full_name='marsMessage.Mars_General_Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trigger', full_name='marsMessage.Mars_General_Order.trigger', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='behavior', full_name='marsMessage.Mars_General_Order.behavior', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='driving_control_order', full_name='marsMessage.Mars_General_Order.driving_control_order', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='marsMessage.Mars_General_Order.waypoints', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled_triggers', full_name='marsMessage.Mars_General_Order.enabled_triggers', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='continuing_order', full_name='marsMessage.Mars_General_Order.continuing_order', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=236,
)


_MARS_MESSAGE = _descriptor.Descriptor(
  name='Mars_Message',
  full_name='marsMessage.Mars_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='marsMessage.Mars_Message.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='marsMessage.Mars_Message.latitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='marsMessage.Mars_Message.longitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='marsMessage.Mars_Message.heading', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='breadcrumb_number', full_name='marsMessage.Mars_Message.breadcrumb_number', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_order_running', full_name='marsMessage.Mars_Message.current_order_running', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orders', full_name='marsMessage.Mars_Message.orders', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=428,
)

_MARS_GENERAL_ORDER.fields_by_name['waypoints'].message_type = waypoint__pb2._WAYPOINT
_MARS_MESSAGE.fields_by_name['orders'].message_type = _MARS_GENERAL_ORDER
DESCRIPTOR.message_types_by_name['Mars_General_Order'] = _MARS_GENERAL_ORDER
DESCRIPTOR.message_types_by_name['Mars_Message'] = _MARS_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mars_General_Order = _reflection.GeneratedProtocolMessageType('Mars_General_Order', (_message.Message,), dict(
  DESCRIPTOR = _MARS_GENERAL_ORDER,
  __module__ = 'athena_mars_pb2'
  # @@protoc_insertion_point(class_scope:marsMessage.Mars_General_Order)
  ))
_sym_db.RegisterMessage(Mars_General_Order)

Mars_Message = _reflection.GeneratedProtocolMessageType('Mars_Message', (_message.Message,), dict(
  DESCRIPTOR = _MARS_MESSAGE,
  __module__ = 'athena_mars_pb2'
  # @@protoc_insertion_point(class_scope:marsMessage.Mars_Message)
  ))
_sym_db.RegisterMessage(Mars_Message)


# @@protoc_insertion_point(module_scope)
