# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver_commander.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msr_common_pb2 as msr__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='driver_commander.proto',
  package='MsrInterfaces',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x64river_commander.proto\x12\rMsrInterfaces\x1a\x10msr_common.proto\"3\n\x0cLLA_Waypoint\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\xa9\x01\n\x13MobilityTaskRequest\x12&\n\x04time\x18\x01 \x01(\x0b\x32\x18.MsrInterfaces.Timestamp\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12,\n\x07request\x18\x03 \x01(\x0e\x32\x1b.MsrInterfaces.MobilityTask\x12.\n\twaypoints\x18\x04 \x03(\x0b\x32\x1b.MsrInterfaces.LLA_Waypoint\"_\n\x1cMobilityTaskProposedSolution\x12\x0f\n\x07task_id\x18\x01 \x01(\x04\x12.\n\twaypoints\x18\x03 \x03(\x0b\x32\x1b.MsrInterfaces.LLA_Waypoint\"_\n\x1dMobilityTaskProposedSolutions\x12>\n\tsolitions\x18\x01 \x03(\x0b\x32+.MsrInterfaces.MobilityTaskProposedSolution\"0\n\x1dMobilityTaskPreferredSolution\x12\x0f\n\x07task_id\x18\x01 \x01(\x04\"u\n\x12MobilityTaskStatus\x12&\n\x04time\x18\x01 \x01(\x0b\x32\x18.MsrInterfaces.Timestamp\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.MsrInterfaces.TaskStatus*9\n\x0cMobilityTask\x12\x08\n\x04STOP\x10\x00\x12\x0c\n\x08WAYPOINT\x10\x01\x12\x11\n\rWAYPOINTROUTE\x10\x02*K\n\nTaskStatus\x12\r\n\tEXECUTING\x10\x00\x12\x08\n\x04\x44ONE\x10\x01\x12\r\n\tDEVIATION\x10\x02\x12\x0b\n\x07PENDING\x10\x03\x12\x08\n\x04HELP\x10\x04\x62\x06proto3')
  ,
  dependencies=[msr__common__pb2.DESCRIPTOR,])

_MOBILITYTASK = _descriptor.EnumDescriptor(
  name='MobilityTask',
  full_name='MsrInterfaces.MobilityTask',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAYPOINT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAYPOINTROUTE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=647,
  serialized_end=704,
)
_sym_db.RegisterEnumDescriptor(_MOBILITYTASK)

MobilityTask = enum_type_wrapper.EnumTypeWrapper(_MOBILITYTASK)
_TASKSTATUS = _descriptor.EnumDescriptor(
  name='TaskStatus',
  full_name='MsrInterfaces.TaskStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXECUTING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVIATION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HELP', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=706,
  serialized_end=781,
)
_sym_db.RegisterEnumDescriptor(_TASKSTATUS)

TaskStatus = enum_type_wrapper.EnumTypeWrapper(_TASKSTATUS)
STOP = 0
WAYPOINT = 1
WAYPOINTROUTE = 2
EXECUTING = 0
DONE = 1
DEVIATION = 2
PENDING = 3
HELP = 4



_LLA_WAYPOINT = _descriptor.Descriptor(
  name='LLA_Waypoint',
  full_name='MsrInterfaces.LLA_Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='MsrInterfaces.LLA_Waypoint.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='MsrInterfaces.LLA_Waypoint.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=110,
)


_MOBILITYTASKREQUEST = _descriptor.Descriptor(
  name='MobilityTaskRequest',
  full_name='MsrInterfaces.MobilityTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='MsrInterfaces.MobilityTaskRequest.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='MsrInterfaces.MobilityTaskRequest.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='MsrInterfaces.MobilityTaskRequest.request', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='MsrInterfaces.MobilityTaskRequest.waypoints', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=282,
)


_MOBILITYTASKPROPOSEDSOLUTION = _descriptor.Descriptor(
  name='MobilityTaskProposedSolution',
  full_name='MsrInterfaces.MobilityTaskProposedSolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='MsrInterfaces.MobilityTaskProposedSolution.task_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='MsrInterfaces.MobilityTaskProposedSolution.waypoints', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=379,
)


_MOBILITYTASKPROPOSEDSOLUTIONS = _descriptor.Descriptor(
  name='MobilityTaskProposedSolutions',
  full_name='MsrInterfaces.MobilityTaskProposedSolutions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='solitions', full_name='MsrInterfaces.MobilityTaskProposedSolutions.solitions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=476,
)


_MOBILITYTASKPREFERREDSOLUTION = _descriptor.Descriptor(
  name='MobilityTaskPreferredSolution',
  full_name='MsrInterfaces.MobilityTaskPreferredSolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='MsrInterfaces.MobilityTaskPreferredSolution.task_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=526,
)


_MOBILITYTASKSTATUS = _descriptor.Descriptor(
  name='MobilityTaskStatus',
  full_name='MsrInterfaces.MobilityTaskStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='MsrInterfaces.MobilityTaskStatus.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='MsrInterfaces.MobilityTaskStatus.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='MsrInterfaces.MobilityTaskStatus.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=645,
)

_MOBILITYTASKREQUEST.fields_by_name['time'].message_type = msr__common__pb2._TIMESTAMP
_MOBILITYTASKREQUEST.fields_by_name['request'].enum_type = _MOBILITYTASK
_MOBILITYTASKREQUEST.fields_by_name['waypoints'].message_type = _LLA_WAYPOINT
_MOBILITYTASKPROPOSEDSOLUTION.fields_by_name['waypoints'].message_type = _LLA_WAYPOINT
_MOBILITYTASKPROPOSEDSOLUTIONS.fields_by_name['solitions'].message_type = _MOBILITYTASKPROPOSEDSOLUTION
_MOBILITYTASKSTATUS.fields_by_name['time'].message_type = msr__common__pb2._TIMESTAMP
_MOBILITYTASKSTATUS.fields_by_name['status'].enum_type = _TASKSTATUS
DESCRIPTOR.message_types_by_name['LLA_Waypoint'] = _LLA_WAYPOINT
DESCRIPTOR.message_types_by_name['MobilityTaskRequest'] = _MOBILITYTASKREQUEST
DESCRIPTOR.message_types_by_name['MobilityTaskProposedSolution'] = _MOBILITYTASKPROPOSEDSOLUTION
DESCRIPTOR.message_types_by_name['MobilityTaskProposedSolutions'] = _MOBILITYTASKPROPOSEDSOLUTIONS
DESCRIPTOR.message_types_by_name['MobilityTaskPreferredSolution'] = _MOBILITYTASKPREFERREDSOLUTION
DESCRIPTOR.message_types_by_name['MobilityTaskStatus'] = _MOBILITYTASKSTATUS
DESCRIPTOR.enum_types_by_name['MobilityTask'] = _MOBILITYTASK
DESCRIPTOR.enum_types_by_name['TaskStatus'] = _TASKSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LLA_Waypoint = _reflection.GeneratedProtocolMessageType('LLA_Waypoint', (_message.Message,), dict(
  DESCRIPTOR = _LLA_WAYPOINT,
  __module__ = 'driver_commander_pb2'
  # @@protoc_insertion_point(class_scope:MsrInterfaces.LLA_Waypoint)
  ))
_sym_db.RegisterMessage(LLA_Waypoint)

MobilityTaskRequest = _reflection.GeneratedProtocolMessageType('MobilityTaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _MOBILITYTASKREQUEST,
  __module__ = 'driver_commander_pb2'
  # @@protoc_insertion_point(class_scope:MsrInterfaces.MobilityTaskRequest)
  ))
_sym_db.RegisterMessage(MobilityTaskRequest)

MobilityTaskProposedSolution = _reflection.GeneratedProtocolMessageType('MobilityTaskProposedSolution', (_message.Message,), dict(
  DESCRIPTOR = _MOBILITYTASKPROPOSEDSOLUTION,
  __module__ = 'driver_commander_pb2'
  # @@protoc_insertion_point(class_scope:MsrInterfaces.MobilityTaskProposedSolution)
  ))
_sym_db.RegisterMessage(MobilityTaskProposedSolution)

MobilityTaskProposedSolutions = _reflection.GeneratedProtocolMessageType('MobilityTaskProposedSolutions', (_message.Message,), dict(
  DESCRIPTOR = _MOBILITYTASKPROPOSEDSOLUTIONS,
  __module__ = 'driver_commander_pb2'
  # @@protoc_insertion_point(class_scope:MsrInterfaces.MobilityTaskProposedSolutions)
  ))
_sym_db.RegisterMessage(MobilityTaskProposedSolutions)

MobilityTaskPreferredSolution = _reflection.GeneratedProtocolMessageType('MobilityTaskPreferredSolution', (_message.Message,), dict(
  DESCRIPTOR = _MOBILITYTASKPREFERREDSOLUTION,
  __module__ = 'driver_commander_pb2'
  # @@protoc_insertion_point(class_scope:MsrInterfaces.MobilityTaskPreferredSolution)
  ))
_sym_db.RegisterMessage(MobilityTaskPreferredSolution)

MobilityTaskStatus = _reflection.GeneratedProtocolMessageType('MobilityTaskStatus', (_message.Message,), dict(
  DESCRIPTOR = _MOBILITYTASKSTATUS,
  __module__ = 'driver_commander_pb2'
  # @@protoc_insertion_point(class_scope:MsrInterfaces.MobilityTaskStatus)
  ))
_sym_db.RegisterMessage(MobilityTaskStatus)


# @@protoc_insertion_point(module_scope)
