# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: principal_athena_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import athena_nike_pb2 as athena__nike__pb2
import athena_artemis_message_pb2 as athena__artemis__message__pb2
import athena_autonomy_pb2 as athena__autonomy__pb2
import athena_mars_pb2 as athena__mars__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='principal_athena_message.proto',
  package='athenaMessages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1eprincipal_athena_message.proto\x12\x0e\x61thenaMessages\x1a\x11\x61thena_nike.proto\x1a\x1c\x61thena_artemis_message.proto\x1a\x15\x61thena_autonomy.proto\x1a\x11\x61thena_mars.proto\"\xb8\x02\n\x18Principal_Athena_Message\x12\x13\n\x0bsender_uuid\x18\x01 \x01(\t\x12\x14\n\x0cmessage_type\x18\x02 \x01(\t\x12\x16\n\x0e\x64\x65stination_id\x18\x03 \x03(\t\x12\x1a\n\x12timestamp_utc_time\x18\x04 \x01(\t\x12\x30\n\x07\x61rtemis\x18\x05 \x03(\x0b\x32\x1f.artemisMessage.Artemis_Message\x12\'\n\x04mars\x18\x06 \x03(\x0b\x32\x19.marsMessage.Mars_Message\x12(\n\x04nike\x18\x07 \x03(\x0b\x32\x1a.nikeMessages.Nike_Message\x12\x38\n\rathena_orders\x18\x08 \x03(\x0b\x32!.athenaOrderMessage.Athena_Ordersb\x06proto3')
  ,
  dependencies=[athena__nike__pb2.DESCRIPTOR,athena__artemis__message__pb2.DESCRIPTOR,athena__autonomy__pb2.DESCRIPTOR,athena__mars__pb2.DESCRIPTOR,])




_PRINCIPAL_ATHENA_MESSAGE = _descriptor.Descriptor(
  name='Principal_Athena_Message',
  full_name='athenaMessages.Principal_Athena_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_uuid', full_name='athenaMessages.Principal_Athena_Message.sender_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_type', full_name='athenaMessages.Principal_Athena_Message.message_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_id', full_name='athenaMessages.Principal_Athena_Message.destination_id', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_utc_time', full_name='athenaMessages.Principal_Athena_Message.timestamp_utc_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artemis', full_name='athenaMessages.Principal_Athena_Message.artemis', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mars', full_name='athenaMessages.Principal_Athena_Message.mars', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nike', full_name='athenaMessages.Principal_Athena_Message.nike', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='athena_orders', full_name='athenaMessages.Principal_Athena_Message.athena_orders', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=454,
)

_PRINCIPAL_ATHENA_MESSAGE.fields_by_name['artemis'].message_type = athena__artemis__message__pb2._ARTEMIS_MESSAGE
_PRINCIPAL_ATHENA_MESSAGE.fields_by_name['mars'].message_type = athena__mars__pb2._MARS_MESSAGE
_PRINCIPAL_ATHENA_MESSAGE.fields_by_name['nike'].message_type = athena__nike__pb2._NIKE_MESSAGE
_PRINCIPAL_ATHENA_MESSAGE.fields_by_name['athena_orders'].message_type = athena__autonomy__pb2._ATHENA_ORDERS
DESCRIPTOR.message_types_by_name['Principal_Athena_Message'] = _PRINCIPAL_ATHENA_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Principal_Athena_Message = _reflection.GeneratedProtocolMessageType('Principal_Athena_Message', (_message.Message,), dict(
  DESCRIPTOR = _PRINCIPAL_ATHENA_MESSAGE,
  __module__ = 'principal_athena_message_pb2'
  # @@protoc_insertion_point(class_scope:athenaMessages.Principal_Athena_Message)
  ))
_sym_db.RegisterMessage(Principal_Athena_Message)


# @@protoc_insertion_point(module_scope)
