# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: athena_nike.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import waypoint_pb2 as waypoint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='athena_nike.proto',
  package='nikeMessages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x61thena_nike.proto\x12\x0cnikeMessages\x1a\x0ewaypoint.proto\"\xce\x01\n\x12Nike_General_Order\x12\x0f\n\x07trigger\x18\x01 \x01(\t\x12\x1c\n\x14weapon_control_order\x18\x02 \x01(\x05\x12\x10\n\x08\x62\x65havior\x18\x03 \x01(\x05\x12-\n\twaypoints\x18\x04 \x03(\x0b\x32\x1a.waypointMessages.Waypoint\x12\x18\n\x10\x65nabled_triggers\x18\x06 \x03(\t\x12\x18\n\x10\x63ontinuing_order\x18\x07 \x01(\t\x12\x14\n\x0c\x61\x63tion_point\x18\x08 \x03(\x02\"\xe3\x02\n\x0cNike_Message\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x15\n\rconnection_ok\x18\x02 \x01(\x08\x12\x12\n\nbatt_level\x18\x03 \x01(\x02\x12\x10\n\x08latitude\x18\x04 \x01(\x02\x12\x11\n\tlongitude\x18\x05 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x06 \x01(\x02\x12\x1c\n\x14\x63urrent_point_number\x18\x07 \x01(\x05\x12\x0f\n\x07\x63\x61n_rth\x18\x08 \x01(\x05\x12\x12\n\nasset_type\x18\t \x01(\x05\x12\x10\n\x08\x61irspace\x18\n \x01(\t\x12\x16\n\x0e\x61irspace_start\x18\x0b \x01(\x05\x12\x15\n\rairspace_stop\x18\x0c \x01(\x05\x12\x0e\n\x06nerfed\x18\r \x01(\x08\x12\x1d\n\x15\x63urrent_order_running\x18\x0e \x01(\t\x12\x30\n\x06orders\x18\x0f \x03(\x0b\x32 .nikeMessages.Nike_General_Orderb\x06proto3')
  ,
  dependencies=[waypoint__pb2.DESCRIPTOR,])




_NIKE_GENERAL_ORDER = _descriptor.Descriptor(
  name='Nike_General_Order',
  full_name='nikeMessages.Nike_General_Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trigger', full_name='nikeMessages.Nike_General_Order.trigger', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon_control_order', full_name='nikeMessages.Nike_General_Order.weapon_control_order', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='behavior', full_name='nikeMessages.Nike_General_Order.behavior', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='nikeMessages.Nike_General_Order.waypoints', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled_triggers', full_name='nikeMessages.Nike_General_Order.enabled_triggers', index=4,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='continuing_order', full_name='nikeMessages.Nike_General_Order.continuing_order', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_point', full_name='nikeMessages.Nike_General_Order.action_point', index=6,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=258,
)


_NIKE_MESSAGE = _descriptor.Descriptor(
  name='Nike_Message',
  full_name='nikeMessages.Nike_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='nikeMessages.Nike_Message.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection_ok', full_name='nikeMessages.Nike_Message.connection_ok', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batt_level', full_name='nikeMessages.Nike_Message.batt_level', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='nikeMessages.Nike_Message.latitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='nikeMessages.Nike_Message.longitude', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='nikeMessages.Nike_Message.altitude', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_point_number', full_name='nikeMessages.Nike_Message.current_point_number', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_rth', full_name='nikeMessages.Nike_Message.can_rth', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_type', full_name='nikeMessages.Nike_Message.asset_type', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airspace', full_name='nikeMessages.Nike_Message.airspace', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airspace_start', full_name='nikeMessages.Nike_Message.airspace_start', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airspace_stop', full_name='nikeMessages.Nike_Message.airspace_stop', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nerfed', full_name='nikeMessages.Nike_Message.nerfed', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_order_running', full_name='nikeMessages.Nike_Message.current_order_running', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orders', full_name='nikeMessages.Nike_Message.orders', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=616,
)

_NIKE_GENERAL_ORDER.fields_by_name['waypoints'].message_type = waypoint__pb2._WAYPOINT
_NIKE_MESSAGE.fields_by_name['orders'].message_type = _NIKE_GENERAL_ORDER
DESCRIPTOR.message_types_by_name['Nike_General_Order'] = _NIKE_GENERAL_ORDER
DESCRIPTOR.message_types_by_name['Nike_Message'] = _NIKE_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nike_General_Order = _reflection.GeneratedProtocolMessageType('Nike_General_Order', (_message.Message,), dict(
  DESCRIPTOR = _NIKE_GENERAL_ORDER,
  __module__ = 'athena_nike_pb2'
  # @@protoc_insertion_point(class_scope:nikeMessages.Nike_General_Order)
  ))
_sym_db.RegisterMessage(Nike_General_Order)

Nike_Message = _reflection.GeneratedProtocolMessageType('Nike_Message', (_message.Message,), dict(
  DESCRIPTOR = _NIKE_MESSAGE,
  __module__ = 'athena_nike_pb2'
  # @@protoc_insertion_point(class_scope:nikeMessages.Nike_Message)
  ))
_sym_db.RegisterMessage(Nike_Message)


# @@protoc_insertion_point(module_scope)
