# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shooter_targeting_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shooter_targeting_message.proto',
  package='shooter',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fshooter_targeting_message.proto\x12\x07shooter\"\xa1\x01\n\rImage_Message\x12\x11\n\tsource_id\x18\x01 \x01(\x03\x12\x11\n\ttarget_id\x18\x02 \x01(\x03\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x13\n\x0bimage_width\x18\x04 \x01(\x03\x12\x14\n\x0cimage_height\x18\x05 \x01(\x03\x12\x16\n\x0eimage_channels\x18\x06 \x01(\x03\x12\x13\n\x0bimage_bytes\x18\x07 \x01(\x0c\"\xd9\x01\n\x12\x43ontact_Properties\x12\x11\n\tsource_id\x18\x01 \x01(\x03\x12\x11\n\ttarget_id\x18\x02 \x01(\x03\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08movement\x18\x04 \x01(\x08\x12\x10\n\x08spectrum\x18\x05 \x01(\t\x12\x16\n\x0e\x63lassification\x18\x06 \x01(\t\x12\x17\n\x0f\x65stimated_range\x18\x07 \x01(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x08 \x01(\x02\x12\x10\n\x08latitude\x18\t \x01(\x01\x12\x11\n\tlongitude\x18\n \x01(\x01\"b\n\x1eSupervised_Engagement_Response\x12\x12\n\nartemis_id\x18\x01 \x01(\x03\x12\x11\n\ttarget_id\x18\x02 \x01(\x03\x12\x19\n\x11\x65ngagement_answer\x18\x03 \x01(\x08\x62\x06proto3')
)




_IMAGE_MESSAGE = _descriptor.Descriptor(
  name='Image_Message',
  full_name='shooter.Image_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_id', full_name='shooter.Image_Message.source_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_id', full_name='shooter.Image_Message.target_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='shooter.Image_Message.confidence', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_width', full_name='shooter.Image_Message.image_width', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_height', full_name='shooter.Image_Message.image_height', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_channels', full_name='shooter.Image_Message.image_channels', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_bytes', full_name='shooter.Image_Message.image_bytes', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=206,
)


_CONTACT_PROPERTIES = _descriptor.Descriptor(
  name='Contact_Properties',
  full_name='shooter.Contact_Properties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_id', full_name='shooter.Contact_Properties.source_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_id', full_name='shooter.Contact_Properties.target_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='shooter.Contact_Properties.confidence', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='movement', full_name='shooter.Contact_Properties.movement', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spectrum', full_name='shooter.Contact_Properties.spectrum', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classification', full_name='shooter.Contact_Properties.classification', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimated_range', full_name='shooter.Contact_Properties.estimated_range', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bearing', full_name='shooter.Contact_Properties.bearing', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='shooter.Contact_Properties.latitude', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='shooter.Contact_Properties.longitude', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=426,
)


_SUPERVISED_ENGAGEMENT_RESPONSE = _descriptor.Descriptor(
  name='Supervised_Engagement_Response',
  full_name='shooter.Supervised_Engagement_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='artemis_id', full_name='shooter.Supervised_Engagement_Response.artemis_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_id', full_name='shooter.Supervised_Engagement_Response.target_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engagement_answer', full_name='shooter.Supervised_Engagement_Response.engagement_answer', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=526,
)

DESCRIPTOR.message_types_by_name['Image_Message'] = _IMAGE_MESSAGE
DESCRIPTOR.message_types_by_name['Contact_Properties'] = _CONTACT_PROPERTIES
DESCRIPTOR.message_types_by_name['Supervised_Engagement_Response'] = _SUPERVISED_ENGAGEMENT_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image_Message = _reflection.GeneratedProtocolMessageType('Image_Message', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE_MESSAGE,
  __module__ = 'shooter_targeting_message_pb2'
  # @@protoc_insertion_point(class_scope:shooter.Image_Message)
  ))
_sym_db.RegisterMessage(Image_Message)

Contact_Properties = _reflection.GeneratedProtocolMessageType('Contact_Properties', (_message.Message,), dict(
  DESCRIPTOR = _CONTACT_PROPERTIES,
  __module__ = 'shooter_targeting_message_pb2'
  # @@protoc_insertion_point(class_scope:shooter.Contact_Properties)
  ))
_sym_db.RegisterMessage(Contact_Properties)

Supervised_Engagement_Response = _reflection.GeneratedProtocolMessageType('Supervised_Engagement_Response', (_message.Message,), dict(
  DESCRIPTOR = _SUPERVISED_ENGAGEMENT_RESPONSE,
  __module__ = 'shooter_targeting_message_pb2'
  # @@protoc_insertion_point(class_scope:shooter.Supervised_Engagement_Response)
  ))
_sym_db.RegisterMessage(Supervised_Engagement_Response)


# @@protoc_insertion_point(module_scope)
