# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: athena_artemis_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='athena_artemis_message.proto',
  package='artemisMessage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x61thena_artemis_message.proto\x12\x0e\x61rtemisMessage\"\x9d\x02\n\x15\x41rtemis_General_Order\x12\x0f\n\x07trigger\x18\x01 \x01(\t\x12\x1c\n\x14weapon_control_order\x18\x02 \x01(\x05\x12\x10\n\x08\x62\x65havior\x18\x03 \x01(\x05\x12\x1b\n\x13select_scan_pattern\x18\x04 \x01(\x05\x12\x37\n\x13\x63reate_scan_pattern\x18\x05 \x03(\x0b\x32\x1a.artemisMessage.Scan_Point\x12\x10\n\x08left_aor\x18\x06 \x01(\x02\x12\x11\n\tright_aor\x18\x07 \x01(\x02\x12\x18\n\x10\x65nabled_triggers\x18\x08 \x03(\t\x12\x18\n\x10\x63ontinuing_order\x18\t \x01(\t\x12\x14\n\x0c\x61\x63tion_point\x18\n \x03(\x02\"K\n\nScan_Point\x12\x14\n\x0cpoint_number\x18\x01 \x01(\x05\x12\x0b\n\x03pan\x18\x02 \x01(\x02\x12\x0c\n\x04tilt\x18\x03 \x01(\x02\x12\x0c\n\x04zoom\x18\x04 \x01(\x02\"\xb1\x02\n\x0f\x41rtemis_Message\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x02\x12\x0f\n\x07heading\x18\x05 \x01(\x02\x12\x15\n\rfire_fan_left\x18\x06 \x01(\x02\x12\x16\n\x0e\x66ire_fan_right\x18\x07 \x01(\x02\x12\x12\n\nammo_count\x18\x08 \x01(\x05\x12\x0f\n\x07ptu_pan\x18\t \x01(\x02\x12\x10\n\x08ptu_tilt\x18\n \x01(\x02\x12\x0c\n\x04zoom\x18\x0b \x01(\x02\x12\x1d\n\x15\x63urrent_order_running\x18\x0c \x01(\t\x12\x35\n\x06orders\x18\r \x03(\x0b\x32%.artemisMessage.Artemis_General_Orderb\x06proto3')
)




_ARTEMIS_GENERAL_ORDER = _descriptor.Descriptor(
  name='Artemis_General_Order',
  full_name='artemisMessage.Artemis_General_Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trigger', full_name='artemisMessage.Artemis_General_Order.trigger', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon_control_order', full_name='artemisMessage.Artemis_General_Order.weapon_control_order', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='behavior', full_name='artemisMessage.Artemis_General_Order.behavior', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='select_scan_pattern', full_name='artemisMessage.Artemis_General_Order.select_scan_pattern', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_scan_pattern', full_name='artemisMessage.Artemis_General_Order.create_scan_pattern', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_aor', full_name='artemisMessage.Artemis_General_Order.left_aor', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_aor', full_name='artemisMessage.Artemis_General_Order.right_aor', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled_triggers', full_name='artemisMessage.Artemis_General_Order.enabled_triggers', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='continuing_order', full_name='artemisMessage.Artemis_General_Order.continuing_order', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_point', full_name='artemisMessage.Artemis_General_Order.action_point', index=9,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=334,
)


_SCAN_POINT = _descriptor.Descriptor(
  name='Scan_Point',
  full_name='artemisMessage.Scan_Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point_number', full_name='artemisMessage.Scan_Point.point_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pan', full_name='artemisMessage.Scan_Point.pan', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tilt', full_name='artemisMessage.Scan_Point.tilt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoom', full_name='artemisMessage.Scan_Point.zoom', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=411,
)


_ARTEMIS_MESSAGE = _descriptor.Descriptor(
  name='Artemis_Message',
  full_name='artemisMessage.Artemis_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='artemisMessage.Artemis_Message.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='artemisMessage.Artemis_Message.latitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='artemisMessage.Artemis_Message.longitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='artemisMessage.Artemis_Message.altitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='artemisMessage.Artemis_Message.heading', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fire_fan_left', full_name='artemisMessage.Artemis_Message.fire_fan_left', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fire_fan_right', full_name='artemisMessage.Artemis_Message.fire_fan_right', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ammo_count', full_name='artemisMessage.Artemis_Message.ammo_count', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ptu_pan', full_name='artemisMessage.Artemis_Message.ptu_pan', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ptu_tilt', full_name='artemisMessage.Artemis_Message.ptu_tilt', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoom', full_name='artemisMessage.Artemis_Message.zoom', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_order_running', full_name='artemisMessage.Artemis_Message.current_order_running', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orders', full_name='artemisMessage.Artemis_Message.orders', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=719,
)

_ARTEMIS_GENERAL_ORDER.fields_by_name['create_scan_pattern'].message_type = _SCAN_POINT
_ARTEMIS_MESSAGE.fields_by_name['orders'].message_type = _ARTEMIS_GENERAL_ORDER
DESCRIPTOR.message_types_by_name['Artemis_General_Order'] = _ARTEMIS_GENERAL_ORDER
DESCRIPTOR.message_types_by_name['Scan_Point'] = _SCAN_POINT
DESCRIPTOR.message_types_by_name['Artemis_Message'] = _ARTEMIS_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Artemis_General_Order = _reflection.GeneratedProtocolMessageType('Artemis_General_Order', (_message.Message,), dict(
  DESCRIPTOR = _ARTEMIS_GENERAL_ORDER,
  __module__ = 'athena_artemis_message_pb2'
  # @@protoc_insertion_point(class_scope:artemisMessage.Artemis_General_Order)
  ))
_sym_db.RegisterMessage(Artemis_General_Order)

Scan_Point = _reflection.GeneratedProtocolMessageType('Scan_Point', (_message.Message,), dict(
  DESCRIPTOR = _SCAN_POINT,
  __module__ = 'athena_artemis_message_pb2'
  # @@protoc_insertion_point(class_scope:artemisMessage.Scan_Point)
  ))
_sym_db.RegisterMessage(Scan_Point)

Artemis_Message = _reflection.GeneratedProtocolMessageType('Artemis_Message', (_message.Message,), dict(
  DESCRIPTOR = _ARTEMIS_MESSAGE,
  __module__ = 'athena_artemis_message_pb2'
  # @@protoc_insertion_point(class_scope:artemisMessage.Artemis_Message)
  ))
_sym_db.RegisterMessage(Artemis_Message)


# @@protoc_insertion_point(module_scope)
