# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: athena_autonomy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import waypoint_pb2 as waypoint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='athena_autonomy.proto',
  package='athenaOrderMessage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x61thena_autonomy.proto\x12\x12\x61thenaOrderMessage\x1a\x0ewaypoint.proto\"\xba\x01\n\x0cWTM_Settings\x12\x10\n\x08wtm_mode\x18\x01 \x01(\x05\x12,\n\x08wtm_area\x18\x02 \x03(\x0b\x32\x1a.waypointMessages.Waypoint\x12\x1c\n\x14weapon_control_order\x18\x03 \x01(\x05\x12\x1a\n\x12\x61pplicable_systems\x18\x04 \x03(\x05\x12\x1e\n\x16\x61pplicable_systems_cot\x18\x05 \x03(\t\x12\x10\n\x08wtm_name\x18\x06 \x01(\t\"\x86\x01\n\rAthena_Orders\x12\x1c\n\x14weapon_control_order\x18\x01 \x01(\x05\x12\x10\n\x08\x62\x65havior\x18\x02 \x01(\x05\x12/\n\x0b\x61rea_points\x18\x03 \x03(\x0b\x32\x1a.waypointMessages.Waypoint\x12\x14\n\x0cgroup_number\x18\x04 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[waypoint__pb2.DESCRIPTOR,])




_WTM_SETTINGS = _descriptor.Descriptor(
  name='WTM_Settings',
  full_name='athenaOrderMessage.WTM_Settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wtm_mode', full_name='athenaOrderMessage.WTM_Settings.wtm_mode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wtm_area', full_name='athenaOrderMessage.WTM_Settings.wtm_area', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weapon_control_order', full_name='athenaOrderMessage.WTM_Settings.weapon_control_order', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applicable_systems', full_name='athenaOrderMessage.WTM_Settings.applicable_systems', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applicable_systems_cot', full_name='athenaOrderMessage.WTM_Settings.applicable_systems_cot', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wtm_name', full_name='athenaOrderMessage.WTM_Settings.wtm_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=248,
)


_ATHENA_ORDERS = _descriptor.Descriptor(
  name='Athena_Orders',
  full_name='athenaOrderMessage.Athena_Orders',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weapon_control_order', full_name='athenaOrderMessage.Athena_Orders.weapon_control_order', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='behavior', full_name='athenaOrderMessage.Athena_Orders.behavior', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area_points', full_name='athenaOrderMessage.Athena_Orders.area_points', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_number', full_name='athenaOrderMessage.Athena_Orders.group_number', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=385,
)

_WTM_SETTINGS.fields_by_name['wtm_area'].message_type = waypoint__pb2._WAYPOINT
_ATHENA_ORDERS.fields_by_name['area_points'].message_type = waypoint__pb2._WAYPOINT
DESCRIPTOR.message_types_by_name['WTM_Settings'] = _WTM_SETTINGS
DESCRIPTOR.message_types_by_name['Athena_Orders'] = _ATHENA_ORDERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WTM_Settings = _reflection.GeneratedProtocolMessageType('WTM_Settings', (_message.Message,), dict(
  DESCRIPTOR = _WTM_SETTINGS,
  __module__ = 'athena_autonomy_pb2'
  # @@protoc_insertion_point(class_scope:athenaOrderMessage.WTM_Settings)
  ))
_sym_db.RegisterMessage(WTM_Settings)

Athena_Orders = _reflection.GeneratedProtocolMessageType('Athena_Orders', (_message.Message,), dict(
  DESCRIPTOR = _ATHENA_ORDERS,
  __module__ = 'athena_autonomy_pb2'
  # @@protoc_insertion_point(class_scope:athenaOrderMessage.Athena_Orders)
  ))
_sym_db.RegisterMessage(Athena_Orders)


# @@protoc_insertion_point(module_scope)
